name: Test code

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape pour récupérer le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Étape pour installer Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: 3.9 

      # Étape pour installer les dépendances du projet
      - name: Install Dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

      # Étape pour télécharger les données
      - name: Download Data
        run: |
          python -c "
          from script import download;
          data = download('https://raw.githubusercontent.com/12alain/python/master/data/billets.csv');
          print(data.head())"
      
      # Étape pour vérifier le formatage du code avec Black
      - name: Run Black
        run: |
          pip install black
          black --check .

      # Étape pour vérifier la qualité du code avec Ruff
      - name: Run Ruff
        run: |
          pip install ruff
          ruff . --select E,W,F

      